#name: Docker Image CI
#
#on:
#  push:
#    branches: [ "master" ]
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Install dependencies
#        run: |
#          ls
#          npm install
#
#      - name: Build app
#        run: npm run build
#
#      - name: Copy build artifacts
#        run: |
#          mkdir -p deploy
#          cp -R dist/* deploy/
#
#      - name: Deploy to server
#        uses: easingthemes/ssh-deploy@v4.1.8
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
#          ARGS: "-rltgoDzvO --delete"
#        with:
#          server: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
##          port: ${{ secrets.PORT }}
#          source: deploy/
#          target: /root/sipi/frontend
#
#  send_message:
#    runs-on: ubuntu-latest
#    needs: build-and-deploy
#    steps:
#      - name: send message
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: ${{ github.workflow }} успешно выполнен!